
export const MOVIE_REQUEST = 'MOVIE_REQUEST'
export const MOVIE_FAIL = 'MOVIE_FAIL'
export const MOVIE_SUCCESS = 'MOVIE_SUCCESS'
export const MOVIE_CAST_REQUEST = 'MOVIE_CAST_REQUEST'
export const MOVIE_CAST_SUCCESS = 'MOVIE+CAST_SUCCESS'

